# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bc29a73e3d51c8f45ef8689aeac9151ab4a1bc4af30988d7cbeb559b35985ab0253d93a66dc55126f64f4a59c7536765d830693dbd67b01872e86b5d0dca3ce

test:
  secret_key_base: 57e8e6c95c754bea1864e87e24910d0c5ecd700991433596e0b169dca56dc831bfae1f9063ed8650012105e1a9b24ec4c6df1de547fa2088f8ebe7cc5a7d17a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
